name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.51.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          playwright install
          pip install pytest-playwright
      - name: Run tests with pytest
        run: |
          pytest tests/ --html=reports/report.html --self-contained-html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: reports/*.html
